### ISSUE TITLE
Heliactyl is allowing to buy only 20% cpu but the max in settings is set to 2000

### ISSUE THREAD

**Issue by RihardKeegi** [Heliactyl/Heliactyl#30]
The same thing happens with server slots, RAM , i can only buy 20% cpu if I try to buy more it gives me an error: MAXCPUEXCEETED

**Comment by tovade** [comment]
Make sure you modified this:

**Comment by RihardKeegi** [comment]
they are set to 20gb ram 2000% cpu 40 servers 20gb disk

**Comment by RihardKeegi** [comment]
![image](https://user-images.githubusercontent.com/75586325/155200540-e35501dc-9445-4f14-9187-935bba62769d.png)

**Comment by pl3xed** [comment]
I know of the problem lmao, it's fixed in heliactyl 11.5.0 and 12.0.0

**Comment by RihardKeegi** [comment]
Okay! Thaks
